name: Daily News

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:
    inputs:
      provider:
        description: "Provider to search"
        required: true
        type: choice
        default: "all"
        options:
          - reddit
          - hackerNews
          - googleNews
          - all
      topic:
        description: "Topic to search"
        required: true
        type: string
        default: "Dogs"

permissions:
  contents: write

jobs:
  aggregate-news:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "21"

      - name: Install dependencies
        run: npm install

      - name: Run aggregator script
        run: node src/index.js ${{inputs.provider}} ${{inputs.topic}}

      - name: Upload news report
        uses: actions/upload-artifact@v4
        with:
          name: news-report
          path: report/*.csv

  # teams-message:
  #   uses: ./.github/workflows/teams_message.yml
  #   with:
  #     TEAMS_WEBHOOK_URL:
  #     GITHUB_RUN_ID: ${{ github.run_id }}
  #     TOPIC: ${{ inputs.topic }}

  discord-message:
    needs: aggregate-news
    uses: ./.github/workflows/discord_message.yml
    with:
      DISCORD_WEBHOOK_URL: https://discord.com/api/webhooks/1442941704285192356/ggvu-RLfdxsN5pmWz3yEfkD280zWhUGGIr6kY6qfMp61HKGXXlxC6QuwnZ29aFFA9Orp
      GITHUB_RUN_ID: ${{ github.run_id }}
      TOPIC: ${{ inputs.topic }}
