name: Run Script
run-name: ${{ github.actor }} is testing out GitHub Actions ðŸš€
on:
  workflow_dispatch:
    inputs:
      provider:
        description: "Provider to search"
        required: true
        type: choice
        default: "reddit"
        options:
          - reddit
          - hackerNews
      topic:
        description: "Topic to search"
        required: true
        type: string

jobs:
  Run-Script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '22'
      - name: Install Dependencies
        run: npm install
      - name: Run Script
        run: |
          npm run ${{inputs.provider}} ${{inputs.topic}}
